# CMake generated Testfile for 
# Source directory: /home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam/inference/tests
# Build directory: /home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/python/gtsam/inference/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(testKey "/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/python/gtsam/inference/tests/testKey")
set_tests_properties(testKey PROPERTIES  _BACKTRACE_TRIPLES "/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/cmake/GtsamTesting.cmake;176;add_test;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam/inference/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam/inference/tests/CMakeLists.txt;0;")
add_test(testLabeledSymbol "/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/python/gtsam/inference/tests/testLabeledSymbol")
set_tests_properties(testLabeledSymbol PROPERTIES  _BACKTRACE_TRIPLES "/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/cmake/GtsamTesting.cmake;176;add_test;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam/inference/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam/inference/tests/CMakeLists.txt;0;")
add_test(testOrdering "/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/python/gtsam/inference/tests/testOrdering")
set_tests_properties(testOrdering PROPERTIES  _BACKTRACE_TRIPLES "/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/cmake/GtsamTesting.cmake;176;add_test;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam/inference/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam/inference/tests/CMakeLists.txt;0;")
add_test(testSymbol "/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/python/gtsam/inference/tests/testSymbol")
set_tests_properties(testSymbol PROPERTIES  _BACKTRACE_TRIPLES "/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/cmake/GtsamTesting.cmake;176;add_test;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam/inference/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam/inference/tests/CMakeLists.txt;0;")
add_test(testVariableSlots "/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/python/gtsam/inference/tests/testVariableSlots")
set_tests_properties(testVariableSlots PROPERTIES  _BACKTRACE_TRIPLES "/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/cmake/GtsamTesting.cmake;176;add_test;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam/inference/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam/inference/tests/CMakeLists.txt;0;")
