# CMake generated Testfile for 
# Source directory: /home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam_unstable/linear/tests
# Build directory: /home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/python/gtsam_unstable/linear/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(testLPSolver "/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/python/gtsam_unstable/linear/tests/testLPSolver")
set_tests_properties(testLPSolver PROPERTIES  _BACKTRACE_TRIPLES "/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/cmake/GtsamTesting.cmake;176;add_test;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam_unstable/linear/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam_unstable/linear/tests/CMakeLists.txt;0;")
add_test(testLinearEquality "/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/python/gtsam_unstable/linear/tests/testLinearEquality")
set_tests_properties(testLinearEquality PROPERTIES  _BACKTRACE_TRIPLES "/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/cmake/GtsamTesting.cmake;176;add_test;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam_unstable/linear/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam_unstable/linear/tests/CMakeLists.txt;0;")
add_test(testQPSolver "/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/python/gtsam_unstable/linear/tests/testQPSolver")
set_tests_properties(testQPSolver PROPERTIES  _BACKTRACE_TRIPLES "/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/cmake/GtsamTesting.cmake;176;add_test;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam_unstable/linear/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam_unstable/linear/tests/CMakeLists.txt;0;")
