# CMake generated Testfile for 
# Source directory: /home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam_unstable/discrete/tests
# Build directory: /home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/python/gtsam_unstable/discrete/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(testCSP "/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/python/gtsam_unstable/discrete/tests/testCSP")
set_tests_properties(testCSP PROPERTIES  _BACKTRACE_TRIPLES "/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/cmake/GtsamTesting.cmake;176;add_test;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam_unstable/discrete/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam_unstable/discrete/tests/CMakeLists.txt;0;")
add_test(testLoopyBelief "/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/python/gtsam_unstable/discrete/tests/testLoopyBelief")
set_tests_properties(testLoopyBelief PROPERTIES  _BACKTRACE_TRIPLES "/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/cmake/GtsamTesting.cmake;176;add_test;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam_unstable/discrete/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam_unstable/discrete/tests/CMakeLists.txt;0;")
add_test(testScheduler "/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/python/gtsam_unstable/discrete/tests/testScheduler")
set_tests_properties(testScheduler PROPERTIES  _BACKTRACE_TRIPLES "/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/cmake/GtsamTesting.cmake;176;add_test;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam_unstable/discrete/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam_unstable/discrete/tests/CMakeLists.txt;0;")
add_test(testSudoku "/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/python/gtsam_unstable/discrete/tests/testSudoku")
set_tests_properties(testSudoku PROPERTIES  _BACKTRACE_TRIPLES "/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/cmake/GtsamTesting.cmake;176;add_test;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam_unstable/discrete/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam_unstable/discrete/tests/CMakeLists.txt;0;")
