# CMake generated Testfile for 
# Source directory: /home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam/hybrid/tests
# Build directory: /home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/python/gtsam/hybrid/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(testGaussianMixture "/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/python/gtsam/hybrid/tests/testGaussianMixture")
set_tests_properties(testGaussianMixture PROPERTIES  _BACKTRACE_TRIPLES "/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/cmake/GtsamTesting.cmake;176;add_test;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam/hybrid/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam/hybrid/tests/CMakeLists.txt;0;")
add_test(testGaussianMixtureFactor "/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/python/gtsam/hybrid/tests/testGaussianMixtureFactor")
set_tests_properties(testGaussianMixtureFactor PROPERTIES  _BACKTRACE_TRIPLES "/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/cmake/GtsamTesting.cmake;176;add_test;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam/hybrid/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam/hybrid/tests/CMakeLists.txt;0;")
add_test(testHybridBayesNet "/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/python/gtsam/hybrid/tests/testHybridBayesNet")
set_tests_properties(testHybridBayesNet PROPERTIES  _BACKTRACE_TRIPLES "/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/cmake/GtsamTesting.cmake;176;add_test;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam/hybrid/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam/hybrid/tests/CMakeLists.txt;0;")
add_test(testHybridBayesTree "/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/python/gtsam/hybrid/tests/testHybridBayesTree")
set_tests_properties(testHybridBayesTree PROPERTIES  _BACKTRACE_TRIPLES "/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/cmake/GtsamTesting.cmake;176;add_test;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam/hybrid/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam/hybrid/tests/CMakeLists.txt;0;")
add_test(testHybridEstimation "/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/python/gtsam/hybrid/tests/testHybridEstimation")
set_tests_properties(testHybridEstimation PROPERTIES  _BACKTRACE_TRIPLES "/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/cmake/GtsamTesting.cmake;176;add_test;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam/hybrid/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam/hybrid/tests/CMakeLists.txt;0;")
add_test(testHybridFactorGraph "/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/python/gtsam/hybrid/tests/testHybridFactorGraph")
set_tests_properties(testHybridFactorGraph PROPERTIES  _BACKTRACE_TRIPLES "/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/cmake/GtsamTesting.cmake;176;add_test;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam/hybrid/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam/hybrid/tests/CMakeLists.txt;0;")
add_test(testHybridGaussianFactorGraph "/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/python/gtsam/hybrid/tests/testHybridGaussianFactorGraph")
set_tests_properties(testHybridGaussianFactorGraph PROPERTIES  _BACKTRACE_TRIPLES "/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/cmake/GtsamTesting.cmake;176;add_test;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam/hybrid/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam/hybrid/tests/CMakeLists.txt;0;")
add_test(testHybridGaussianISAM "/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/python/gtsam/hybrid/tests/testHybridGaussianISAM")
set_tests_properties(testHybridGaussianISAM PROPERTIES  _BACKTRACE_TRIPLES "/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/cmake/GtsamTesting.cmake;176;add_test;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam/hybrid/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam/hybrid/tests/CMakeLists.txt;0;")
add_test(testHybridNonlinearFactorGraph "/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/python/gtsam/hybrid/tests/testHybridNonlinearFactorGraph")
set_tests_properties(testHybridNonlinearFactorGraph PROPERTIES  _BACKTRACE_TRIPLES "/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/cmake/GtsamTesting.cmake;176;add_test;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam/hybrid/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam/hybrid/tests/CMakeLists.txt;0;")
add_test(testHybridNonlinearISAM "/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/python/gtsam/hybrid/tests/testHybridNonlinearISAM")
set_tests_properties(testHybridNonlinearISAM PROPERTIES  _BACKTRACE_TRIPLES "/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/cmake/GtsamTesting.cmake;176;add_test;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam/hybrid/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam/hybrid/tests/CMakeLists.txt;0;")
add_test(testHybridValues "/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/python/gtsam/hybrid/tests/testHybridValues")
set_tests_properties(testHybridValues PROPERTIES  _BACKTRACE_TRIPLES "/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/cmake/GtsamTesting.cmake;176;add_test;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam/hybrid/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam/hybrid/tests/CMakeLists.txt;0;")
