# CMake generated Testfile for 
# Source directory: /home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam/sfm/tests
# Build directory: /home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/python/gtsam/sfm/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(testBinaryMeasurement "/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/python/gtsam/sfm/tests/testBinaryMeasurement")
set_tests_properties(testBinaryMeasurement PROPERTIES  _BACKTRACE_TRIPLES "/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/cmake/GtsamTesting.cmake;176;add_test;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam/sfm/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam/sfm/tests/CMakeLists.txt;0;")
add_test(testMFAS "/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/python/gtsam/sfm/tests/testMFAS")
set_tests_properties(testMFAS PROPERTIES  _BACKTRACE_TRIPLES "/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/cmake/GtsamTesting.cmake;176;add_test;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam/sfm/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam/sfm/tests/CMakeLists.txt;0;")
add_test(testSfmData "/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/python/gtsam/sfm/tests/testSfmData")
set_tests_properties(testSfmData PROPERTIES  _BACKTRACE_TRIPLES "/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/cmake/GtsamTesting.cmake;176;add_test;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam/sfm/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam/sfm/tests/CMakeLists.txt;0;")
add_test(testSfmTrack "/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/python/gtsam/sfm/tests/testSfmTrack")
set_tests_properties(testSfmTrack PROPERTIES  _BACKTRACE_TRIPLES "/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/cmake/GtsamTesting.cmake;176;add_test;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam/sfm/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam/sfm/tests/CMakeLists.txt;0;")
add_test(testShonanAveraging "/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/python/gtsam/sfm/tests/testShonanAveraging")
set_tests_properties(testShonanAveraging PROPERTIES  _BACKTRACE_TRIPLES "/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/cmake/GtsamTesting.cmake;176;add_test;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam/sfm/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam/sfm/tests/CMakeLists.txt;0;")
add_test(testShonanFactor "/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/python/gtsam/sfm/tests/testShonanFactor")
set_tests_properties(testShonanFactor PROPERTIES  _BACKTRACE_TRIPLES "/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/cmake/GtsamTesting.cmake;176;add_test;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam/sfm/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam/sfm/tests/CMakeLists.txt;0;")
add_test(testShonanGaugeFactor "/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/python/gtsam/sfm/tests/testShonanGaugeFactor")
set_tests_properties(testShonanGaugeFactor PROPERTIES  _BACKTRACE_TRIPLES "/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/cmake/GtsamTesting.cmake;176;add_test;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam/sfm/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam/sfm/tests/CMakeLists.txt;0;")
add_test(testTranslationFactor "/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/python/gtsam/sfm/tests/testTranslationFactor")
set_tests_properties(testTranslationFactor PROPERTIES  _BACKTRACE_TRIPLES "/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/cmake/GtsamTesting.cmake;176;add_test;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam/sfm/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam/sfm/tests/CMakeLists.txt;0;")
