# CMake generated Testfile for 
# Source directory: /home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam/sam/tests
# Build directory: /home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/python/gtsam/sam/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(testBearingFactor "/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/python/gtsam/sam/tests/testBearingFactor")
set_tests_properties(testBearingFactor PROPERTIES  _BACKTRACE_TRIPLES "/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/cmake/GtsamTesting.cmake;176;add_test;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam/sam/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam/sam/tests/CMakeLists.txt;0;")
add_test(testBearingRangeFactor "/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/python/gtsam/sam/tests/testBearingRangeFactor")
set_tests_properties(testBearingRangeFactor PROPERTIES  _BACKTRACE_TRIPLES "/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/cmake/GtsamTesting.cmake;176;add_test;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam/sam/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam/sam/tests/CMakeLists.txt;0;")
add_test(testRangeFactor "/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/python/gtsam/sam/tests/testRangeFactor")
set_tests_properties(testRangeFactor PROPERTIES  _BACKTRACE_TRIPLES "/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/cmake/GtsamTesting.cmake;176;add_test;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam/sam/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam/sam/tests/CMakeLists.txt;0;")
add_test(testSerializationSam "/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/python/gtsam/sam/tests/testSerializationSam")
set_tests_properties(testSerializationSam PROPERTIES  _BACKTRACE_TRIPLES "/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/cmake/GtsamTesting.cmake;176;add_test;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam/sam/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/kody/SLAM/factor-graph-slam-project/code/gtsam/gtsam-develop/gtsam/sam/tests/CMakeLists.txt;0;")
